# aibuilder/llm_client.py
# FloMatrix AI Builder – LLM client
#
# This module wraps the OpenAI client and exposes a single class:
#   LLMClient
# with one main method:
#   await client.generate_code(prompt: str) -> str
#
# It is written so that:
#  - If OPENAI_API_KEY is NOT set, it still works and returns a stub.
#  - If OPENAI_API_KEY IS set, it will call the OpenAI ChatCompletion API
#    using your configured model.

import os
import asyncio
from typing import Optional

import openai


class LLMClient:
    """
    Thin wrapper around OpenAI for the FloMatrix AI Builder.

    Usage:

        client = LLMClient()
        code = await client.generate_code(prompt)

    """

    def __init__(self, api_key: Optional[str] = None, model: Optional[str] = None) -> None:
        # Pick up key from argument or environment
        self.api_key = api_key or os.getenv("OPENAI_API_KEY")
        # Default model – you can change this later if you like
        self.model = model or os.getenv("FLOMATRIX_LLM_MODEL", "gpt-4.1-mini")

        if self.api_key:
            openai.api_key = self.api_key
            self.enabled = True
        else:
            # We still allow the service to start, but we will return stub code.
            self.enabled = False

    # ------------------------------------------------------------------
    # Public async API
    # ------------------------------------------------------------------
    async def generate_code(self, prompt: str) -> str:
        """
        Main entrypoint used by the AI Builder routes.

        Returns a full file of code as a string.
        If no API key is configured, it returns a stub file that clearly
        indicates the LLM is offline.
        """
        if not self.enabled:
            return self._stub_response(prompt)

        # Run the blocking OpenAI call in a thread so FastAPI can remain async.
        loop = asyncio.get_running_loop()
        return await loop.run_in_executor(None, self._generate_code_sync, prompt)

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------
    def _stub_response(self, prompt: str) -> str:
        """
        Used when OPENAI_API_KEY is not set. Keeps the system usable
        without blowing up.
        """
        header = (
            "// [AIB] LLM is currently OFFLINE – no OPENAI_API_KEY configured.\n"
            "// This file was generated by the fallback stub in llm_client.py.\n"
            "// Prompt that would have been sent to the LLM is included below\n"
            "// so you can see what the system is doing.\n\n"
        )
        commented_prompt = "\n".join(f"// {line}" for line in prompt.splitlines())
        return header + commented_prompt + "\n"

    def _generate_code_sync(self, prompt: str) -> str:
        """
        Synchronous OpenAI call. This is wrapped by generate_code()
        using run_in_executor so the FastAPI app stays non-blocking.
        """
        system_message = (
            "You are the FloMatrix AI Builder. "
            "You ONLY output complete files (no snippets). "
            "Follow the project blueprint, respect file paths, and include "
            "clear header comments and integration notes in the code where helpful."
        )

        # Using the ChatCompletion compatibility API from the OpenAI Python SDK.
        # If you later want to move to the new Responses API, we can update this.
        response = openai.ChatCompletion.create(
            model=self.model,
            messages=[
                {"role": "system", "content": system_message},
                {"role": "user", "content": prompt},
            ],
            temperature=0.15,
        )

        # Extract the assistant message text
        try:
            text = response["choices"][0]["message"]["content"]
        except Exception:
            text = "// [AIB] Error: could not parse LLM response.\n"

        # Always return a string – never None
        return text or "// [AIB] Empty response from LLM.\n"
